name: build_pages 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: sudo apt-get install -y doxygen
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mkdocs_custom_fences
      - run: pip install markdown-include
      - run: pip install mkdoxy
      - run: pip install mkdocs_puml
      - run: |
            cp */DOC* docs/docs | true
            cp */*/DOC* docs/docs | true
            cp */*/*/DOC* docs/docs | true
            mv docs/docs/DOC_DED_PD_Project_Description.md docs/docs/index.md
            cd docs/ 
            mkdocs gh-deploy --force