name: Build and release Latex files

on:
    push:
      branches: [ "main" ]
      paths: 
        - /Management_Development/coding_rules
    pull_request:
      branches: [ "main" ]
 
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Build Latex files
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: ${{github.workspace}}/
        root_file: |
          Management_Development/coding_rules/DOC_MAD_SR_coding_rules.tex
        work_in_root_file_dir: true
    - name: Create a prerelease
      if: ${{ github.ref == 'refs/heads/main' }} # pre release only on main
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latex PDF"
        files: |
          Management_Development/coding_rules/DOC_MAD_SR_coding_rules.pdf
